; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "v.h"
#define MyAppName "bili x86"
#define MyAppPublisher "lifegpc"
#define MyAppURL "https:\\github.com\lifegpc\bili"
#define MyAppExeName "start.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5F2B56DE-6400-4AF2-944A-C740BC1A526B}
AppName={#MyAppName}
AppVersion={#MyAppVername}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesAllowed=x86 x64
DefaultDirName={code:GetDefaultInstallRoot}\{#MyAppName}
DefaultGroupName={#MyAppName} x86
DisableProgramGroupPage=yes
LicenseFile=LICENSE
OutputDir=.
OutputBaseFilename=bili_{#MyAppVername}_windows_x86
Compression=lzma
SolidCompression=yes
VersionInfoVersion={#MyAppVersion}
UninstallDisplayName={#MyAppName}
AppCopyright=Copyright 2019-2020 lifegpc
SetupIconFile=..\bili\icon\favicon.ico
UninstallDisplayIcon=..\bili\icon\favicon.ico

[code]
function GetDefaultInstallRoot(Param: String): String;
begin
    if ((GetWindowsVersion shr 16) >= $0600) then
        Result := ExpandConstant('{userappdata}')
    else  
        Result := ExpandConstant('{pf}');
end;

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: zh_CN; MessagesFile: Languages\ChineseSimplified.isl
Name: zh_TW; MessagesFile: Languages\ChineseTraditional.isl
Name: ja;    MessagesFile: compiler:Languages\Japanese.isl

[CustomMessages]
ViewChangelog=View changelog
zh_CN.ViewChangelog=查看更新日志
zh_TW.ViewChangelog=檢視更新紀錄檔
ja.ViewChangelog=変更ログの表示

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "x86\*.bat"; DestDir: "{app}";
Source: "..\bili\embeddedpython_x86.bat"; DestDir: "{app}";
Source: "..\bili\python_x86\*"; DestDir: "{app}\python_x86"; Excludes: "*__pycache__\*"; Flags: recursesubdirs;
Source: "..\bili\*.py"; DestDir: "{app}"; Excludes: "prepare.py,v.py";
Source: "..\bili\file\*.py"; DestDir: "{app}\file";
Source: "..\bili\webui\*.py"; DestDir: "{app}\webui";
Source: "..\bili\webui\api\*.py"; DestDir: "{app}\webui\api";
Source: "..\bili\webui\extractor\*.py"; DestDir: "{app}\webui\extractor";
Source: "..\bili\webui\page\*.py"; DestDir: "{app}\webui\page";
Source: "..\bili\requirements.txt"; DestDir: "{app}";
Source: "x86\aria2c.exe"; DestDir: "{app}";
Source: "chromedriver.exe"; DestDir: "{app}";
Source: "x86\ffmpeg.exe"; DestDir: "{app}";
Source: "LICENSE"; DestDir: "{app}";
Source: "README.html"; DestDir: "{app}"; Flags: isreadme
Source: "version.txt"; DestDir: "{app}";
Source: "changelog.txt"; DestDir: "{app}";
Source: "Language\*"; DestDir: "{app}\Language";
Source: "webuihtml\*"; DestDir: "{app}\webuihtml";
Source: "webuihtml\css\*"; DestDir: "{app}\webuihtml\css";
Source: "webuihtml\csso\*"; DestDir: "{app}\webuihtml\csso";
Source: "webuihtml\js\*"; DestDir: "{app}\webuihtml\js";
Source: "webuihtml\jso\*"; DestDir: "{app}\webuihtml\jso";
Source: "webuihtml\json\*"; DestDir: "{app}\webuihtml\json";
Source: "icon\*"; DestDir: "{app}\icon";
Source: "..\bili\icon\*.ico"; DestDir: "{app}\icon";
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}\bili x86"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon\favicon.ico";
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\icon\favicon.ico";
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon; IconFilename: "{app}\icon\favicon.ico";
Name: "{commonprograms}\{#MyAppName}\setsettings x86"; Filename: "{app}\setsettings.bat"; IconFilename: "{app}\icon\favicon.ico";
Name: "{commonprograms}\{#MyAppName}\filter x86"; Filename: "{app}\filter.bat"; IconFilename: "{app}\icon\favicon.ico";
Name: "{commonprograms}\{#MyAppName}\startwebui x86"; Filename: "{app}\startwebui.bat"; IconFilename: "{app}\icon\favicon.ico";
Name: "{commonprograms}\{#MyAppName}\bili README x86"; Filename: "{app}\README.html"

[Run]
Filename: "{app}\setsettings.bat"; Description: "{cm:LaunchProgram,setsettings.bat}"; Flags: nowait postinstall skipifsilent unchecked
Filename: "{app}\changelog.txt"; Description: "{cm:ViewChangelog}"; Flags: nowait postinstall skipifsilent shellexec

